version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_hyper_cas
    # user: localstack
    ports:
      - '4563-4584:4563-4584'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.tmp:/tmp'
      - '/var/run/docker.sock:/var/run/docker.sock'
